module.exports = {
    RESPONSE_UNAUTHORIZED: 401,
    RESPONSE_NOT_FOUND: 404,
    RESPONSE_BAD_REQUEST: 400,
    RESPONSE_CREATE_SUCCESS: 201,
    RESPONSE_OK: 200,
    RESPONSE_UPDATE_SUCCESS: 200,
    RESPONSE_DELETE_SUCCESS: 200,
};
